from config import DANYLO_DEFAULT_CHAT_ID

LYST_COUNTRIES = ["IT", "PL", "US", "GB"]
LYST_PAGE_SCRAPE = True
LYST_URL_TIMEOUT_SEC = 1800
LYST_STALL_TIMEOUT_SEC = 1800

BASE_URLS = [
    { 
        "url": "https://www.lyst.com/shop/mens-shoes/?designer_slug=eytys&designer_slug=viron&designer_slug=vinnys&designer_slug=sapio&designer_slug=ranra&designer_slug=random-identities&designer_slug=ninamounah&designer_slug=namesake&designer_slug=hereu-designer&designer_slug=grenson&designer_slug=drae&designer_slug=copenhagen&designer_slug=a-diciannoveventitre&designer_slug=kleman&designer_slug=tiger-of-sweden&designer_slug=nanamica&designer_slug=marsell&designer_slug=norse-projects-arktisk&designer_slug=drae&designer_slug=maison-martin-margiela&designer_slug=magliano&designer_slug=mm6-by-maison-martin-margiela&designer_slug=camperlab&designer_slug=yume_yume&designer_slug=dries-van-noten&designer_slug=our-legacy&designer_slug=stefan-cooke&designer_slug=adieu&designer_slug=c2h4&designer_slug=lanvin&designer_slug=acne&designer_slug=a_cold_wall&designer_slug=raf-simons&designer_slug=raf-simons-runner&designer_slug=axel-arigato&designer_slug=y-3&designer_slug=prada&designer_slug=roa-designer&designer_slug=wooyoungmi&designer_slug=maison-margiela-x-reebok&designer_slug=424&designer_slug=jil-sander&designer_slug=juunj&designer_slug=kenzo&designer_slug=oamc&designer_slug=1017-alyx-9sm&designer_slug=officine-creative&designer_slug=marine-serre&designer_slug=salomon&designer_slug=moncler&designer_slug=maison-mihara-yasuhiro-designer&designer_slug=ziggy-chen&designer_slug=comme-des-garcons&designer_slug=ami&designer_slug=rick-owens-drkshdw&designer_slug=marni&designer_slug=boris-bidjan-saberi-11&designer_slug=merrell&designer_slug=norse-projects&designer_slug=demon-designer&designer_slug=toga-virilis&designer_slug=gucci&designer_slug=kiko-kostadinov&designer_slug=fracap&designer_slug=golden-goose-deluxe-brand&designer_slug=sacai&designer_slug=ann-demeulemeester&designer_slug=diemme&designer_slug=gmbh&designer_slug=rombaut&designer_slug=both-paris&designer_slug=stone-island&designer_slug=jacquemus&designer_slug=jw-anderson&designer_slug=givenchy&designer_slug=sandro&designer_slug=hender-scheme&designer_slug=buttero&designer_slug=bottega-veneta&designer_slug=alexander-mcqueen&designer_slug=balenciaga&designer_slug=44-label-group&designer_slug=gr10k&designer_slug=uma-wang&designer_slug=undercover&designer_slug=iro&designer_slug=ganni&designer_slug=ernest-w-baker&designer_slug=andersson-bell-designer&discount_from=60&final_price_from=0&final_price_to=250&instock_size=size.footwear.eu.u.40&instock_size=size.footwear.eu.u.40%275&instock_size=size.footwear.eu.u.41&sizes=IT+40.0&sizes=IT+40.5&sizes=IT+41.0&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID,
        "min_sale": 50,
        "url_name": "Grotesk Shoes"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=wooyoungmi&designer_slug=sulvam-designer&designer_slug=willy-chavarria-designer&designer_slug=tondolo&designer_slug=taiga-takahashi&designer_slug=tanaka-designer&designer_slug=stefan-cooke&designer_slug=stella-mccartney&designer_slug=situationist&designer_slug=small-talk-studio&designer_slug=secondlayer&designer_slug=saif-ud-deen&designer_slug=sankuanz&designer_slug=namacheko&designer_slug=adererror&designer_slug=egonlab&designer_slug=mugler&designer_slug=random-identities&designer_slug=m-i-s-b-h-v&designer_slug=eckhaus-latta&designer_slug=heliot-emil&designer_slug=undercover&designer_slug=sc103&designer_slug=ludovic-de-saint-sernin&designer_slug=ottolinger-designer&designer_slug=song-for-the-mute&designer_slug=uma-wang&designer_slug=dion-lee&designer_slug=jan-jan-van-essche&designer_slug=henrik-vibskov&designer_slug=feng-chen-wang-designer&designer_slug=givenchy&designer_slug=studio-nicholson&designer_slug=acne&designer_slug=ranra&designer_slug=rohe&designer_slug=amomento&designer_slug=meryll-rogge&designer_slug=carlota-barrera&designer_slug=han-kjobenhavn&designer_slug=affxwrks&designer_slug=alexander-wang&designer_slug=maisie-wilen&designer_slug=bianca-saunders&designer_slug=takahiromiyashita-thesoloist&designer_slug=saintwoods&designer_slug=berner-kuhl&designer_slug=arturo-obegero&designer_slug=spencer-badu&designer_slug=monitaly&designer_slug=44-label-group&designer_slug=filippa-k&designer_slug=saul-nash&designer_slug=serapis&designer_slug=frenckenberger&designer_slug=charles-jeffrey&designer_slug=we11done&designer_slug=mm6-by-maison-martin-margiela&designer_slug=maison-martin-margiela&designer_slug=marine-serre&designer_slug=luar-designer&designer_slug=soulland&designer_slug=dries-van-noten&designer_slug=chopova-lowena&designer_slug=fiorucci&designer_slug=bryan-jimenez&designer_slug=cormio&designer_slug=lownn&designer_slug=nemen-designer&designer_slug=lost-daze&designer_slug=rhude-designer&designer_slug=seekings&designer_slug=haulier&designer_slug=howlin-by-morrison&designer_slug=kanghyuk&designer_slug=kngsley&designer_slug=visvim&designer_slug=remi-relief&designer_slug=nanushka&discount_from=60&final_price_to=200&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.t-shirt.international.m&instock_size=size.t-shirt.international.s&instock_size=size.t-shirt.international.l&instock_size=size.jacket.eu.m.46&instock_size=size.jacket.eu.m.48&instock_size=size.jacket.eu.m.50&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.shorts.eu.m.46&instock_size=size.shorts.eu.m.48&instock_size=size.coat.eu.m.48&instock_size=size.coat.eu.m.52&sizes=M&sizes=L&sizes=S&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Main brands"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=anna-sui&designer_slug=fce&designer_slug=magliano&designer_slug=kijun&designer_slug=fax-copy-express&designer_slug=satoshi-nakamoto&designer_slug=darkpark&designer_slug=recto-designer&designer_slug=eytys&designer_slug=isaac-sellam&designer_slug=vetements&designer_slug=hed-mayner-designer&designer_slug=facetasm&designer_slug=denim-tears&designer_slug=daiwa-pier39&designer_slug=courreges&designer_slug=coperni&designer_slug=b1archive&designer_slug=alchemist&designer_slug=afb-designer&designer_slug=1989-studio&designer_slug=032c&designer_slug=424-on-fairfax&designer_slug=66-north&designer_slug=thug-club&designer_slug=south2-west8&designer_slug=sophnet&designer_slug=sasquatchfabrix&designer_slug=maison-mihara-yasuhiro-designer&designer_slug=damir-doma&designer_slug=daniel-w-fletcher&designer_slug=martine-rose&designer_slug=dbyd&designer_slug=_jl-al_&designer_slug=deadwood-designer&designer_slug=pam-perks-and-mini&designer_slug=pdf&designer_slug=ann-demeulemeester&designer_slug=kapital&designer_slug=kidill&designer_slug=by-parrar&designer_slug=luu-an&designer_slug=luu-dan&designer_slug=goopimade&designer_slug=saint-mxxxxxx&designer_slug=saint-michael&designer_slug=jw-anderson&designer_slug=cole-buxton&designer_slug=raf-simons&designer_slug=m-i-s-b-h-v&designer_slug=gr10k&designer_slug=uma-wang&designer_slug=ziggy-chen&designer_slug=entire-studios&designer_slug=kiko-kostadinov&designer_slug=tanaka-designer&designer_slug=a-better-mistake&designer_slug=rick-owens&designer_slug=pyer-moss&designer_slug=veilance&designer_slug=cav-empt&designer_slug=maharishi&designer_slug=lueder&designer_slug=casey-casey&designer_slug=document&designer_slug=ccp-designer&designer_slug=gimaguas&designer_slug=maryam-nassir-zadeh&designer_slug=schnaydermans&designer_slug=story-mfg&designer_slug=toogood&designer_slug=4sdesigns&designer_slug=roa-designer&designer_slug=stone-island-shadow-project&designer_slug=norse-projects-arktisk&designer_slug=toga&designer_slug=kuro&designer_slug=suicoke&designer_slug=abra&designer_slug=another-aspect&designer_slug=n-hoolywood&designer_slug=undercoverism-designer&designer_slug=hyein-seo&designer_slug=the-viridi-anne&designer_slug=jacquemus&designer_slug=soshiotsuki&designer_slug=jean-paul-gaultier&discount_from=60&final_price_to=200&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.t-shirt.international.m&instock_size=size.t-shirt.international.s&instock_size=size.t-shirt.international.l&instock_size=size.jacket.eu.m.46&instock_size=size.jacket.eu.m.48&instock_size=size.jacket.eu.m.50&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.shorts.eu.m.46&instock_size=size.shorts.eu.m.48&instock_size=size.coat.eu.m.48&instock_size=size.coat.eu.m.52&sizes=M&sizes=L&sizes=S&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Main brands [2]"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=cordera&designer_slug=hokita&designer_slug=vaquera&designer_slug=camiel-fortgens&designer_slug=tsau&designer_slug=y-3&designer_slug=carnet-archive&designer_slug=julius&designer_slug=vitelli-designer&designer_slug=peter-do&designer_slug=who-decides-war&designer_slug=lemaire-designerr&designer_slug=ganni&designer_slug=our-legacy&designer_slug=carne-bollente&designer_slug=kusikohc&designer_slug=issey-miyake-homme-plisse&designer_slug=objects-iv-life&designer_slug=andersson-bell-designer&designer_slug=c2h4&designer_slug=oamc&designer_slug=y-project&designer_slug=acronym&designer_slug=stone-island&designer_slug=boris-bidjan-saberi-11&designer_slug=ambush&designer_slug=and-wander&designer_slug=fce&designer_slug=byborre&designer_slug=doublet-designer&designer_slug=juunj&designer_slug=coperni&designer_slug=nicolas-andreas-taralis&designer_slug=post-archive-faction-paf&designer_slug=le17septembre&designer_slug=hodakova&designer_slug=hh-118389225&designer_slug=haal&designer_slug=gentle-fullness&designer_slug=eastwood-danso&designer_slug=dingyun-zhang&designer_slug=cotton-citizen&designer_slug=cornerstone&designer_slug=commission&designer_slug=comfy-outdoor-garment&designer_slug=cobra-sc&designer_slug=chenpeng&designer_slug=christian-dada&designer_slug=boramy-viguier&designer_slug=bless&designer_slug=birrot&designer_slug=arnar-mar-jonsson&designer_slug=archival-reinvent&designer_slug=bethany-williams&designer_slug=apc&designer_slug=andrej-gronau&designer_slug=alled-martinez&designer_slug=aie&designer_slug=adyar&designer_slug=abaga-velli&designer_slug=yoshio-kubo&designer_slug=xlim&designer_slug=willy-chavarria-designer&designer_slug=walter-van-beirendonck&designer_slug=styland&designer_slug=a-diciannoveventitre&designer_slug=hgbb-studio&designer_slug=cmmawear&designer_slug=uncertain-factor&designer_slug=maximilian-davis&designer_slug=the-product&designer_slug=mr-saturday&designer_slug=vein&designer_slug=meanswhile-designer&designer_slug=nrmous&designer_slug=sport-b-by-agnes-b&designer_slug=gmbh&designer_slug=satta-designer&designer_slug=sage-nation&designer_slug=rough&designer_slug=robyn-lynch&discount_from=60&final_price_to=200&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.t-shirt.international.m&instock_size=size.t-shirt.international.s&instock_size=size.t-shirt.international.l&instock_size=size.jacket.eu.m.46&instock_size=size.jacket.eu.m.48&instock_size=size.jacket.eu.m.50&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.shorts.eu.m.46&instock_size=size.shorts.eu.m.48&instock_size=size.coat.eu.m.48&instock_size=size.coat.eu.m.52&sizes=M&sizes=L&sizes=S&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Main brands [3]"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=louis-gabriel-nouchi&designer_slug=rough&designer_slug=rier&designer_slug=rainmaker-kyoto&designer_slug=paloma-wool&designer_slug=other-uk&designer_slug=omar-afridi&designer_slug=nuba&designer_slug=nullus&designer_slug=noma-td&designer_slug=nicholas-daley&designer_slug=needles&designer_slug=namesake&designer_slug=nanamica&designer_slug=martin-asbjorn&designer_slug=mastermind-world&designer_slug=maiden-name&designer_slug=lesugiatelier&designer_slug=international-gallery-beams&designer_slug=craig-green&designer_slug=strongthe&designer_slug=hope&designer_slug=yaku&designer_slug=holzweiler&designer_slug=simone-rocha&designer_slug=johnlawrencesullivan&designer_slug=gauchere&designer_slug=mainlinerusfrcadef&designer_slug=balenciaga&designer_slug=yohji-yamamoto&designer_slug=cout-de-la-liberte&designer_slug=rier&designer_slug=paura&designer_slug=paly&designer_slug=olly-shinder&designer_slug=nili-lotan&designer_slug=mlga&designer_slug=marina-yee&designer_slug=givenchy&designer_slug=kolor&designer_slug=juntae-kim&designer_slug=jordanluca&designer_slug=jiyongkim&designer_slug=_jl-al_&designer_slug=jl-al&designer_slug=isa-boulder&designer_slug=gimaguas&designer_slug=frei-mut&designer_slug=flaneur&designer_slug=croquis&designer_slug=cole-buxton&designer_slug=cmmn-swdn&designer_slug=charlie-constantinou&designer_slug=ceec&designer_slug=boris-bidjan-saberi&designer_slug=blst&designer_slug=blaest&designer_slug=av-vattev&designer_slug=another-aspect&designer_slug=airei&designer_slug=agolde&designer_slug=agnona&designer_slug=achilles-ion-gabriel&designer_slug=act-no1&designer_slug=low-classic&designer_slug=marni&designer_slug=aaspectrum&designer_slug=praying&designer_slug=rier&designer_slug=paly&designer_slug=vtmnts&designer_slug=mhl-by-margaret-howell&designer_slug=margaret-howell&designer_slug=meta-campania-collective&designer_slug=jil-sander&designer_slug=hysteric-glamour&designer_slug=applied-art-forms&designer_slug=aaron-esh&designer_slug=forma&designer_slug=ahluwalia&designer_slug=isabel-benenato&designer_slug=1017-alyx-9sm&designer_slug=toga-virilis&designer_slug=rrr123&designer_slug=random-identities&designer_slug=prototypes&designer_slug=pet-tree-kor&designer_slug=our-legacy&discount_from=60&final_price_to=200&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.t-shirt.international.m&instock_size=size.t-shirt.international.s&instock_size=size.t-shirt.international.l&instock_size=size.jacket.eu.m.46&instock_size=size.jacket.eu.m.48&instock_size=size.jacket.eu.m.50&instock_size=size.pants.eu.m.48&instock_size=size.pants.eu.m.46&instock_size=size.shorts.eu.m.46&instock_size=size.shorts.eu.m.48&instock_size=size.coat.eu.m.48&instock_size=size.coat.eu.m.52&sizes=M&sizes=L&sizes=S&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Main brands [4]"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=ys-yohji-yamamoto&designer_slug=ouat&designer_slug=yleve&designer_slug=ys-for-men&designer_slug=the-product&designer_slug=ouat&designer_slug=vein&designer_slug=bed-jw-ford&designer_slug=meanswhile-designer&designer_slug=nrmous&designer_slug=kolor&designer_slug=maison-mihara-yasuhiro-designer&designer_slug=fumito-ganryu&designer_slug=acronym&designer_slug=kozaburo&designer_slug=kaptain-sunshine&designer_slug=visvim&designer_slug=wtaps&designer_slug=99-is&designer_slug=devoa&designer_slug=attachment&designer_slug=sacai&designer_slug=issey-miyake&designer_slug=saul-nash&designer_slug=issey-miyake-homme-plisse&designer_slug=berner-kuhl&designer_slug=undercoverism-designer&designer_slug=yohji-yamamoto&designer_slug=peter-do&designer_slug=cordera&designer_slug=julius&designer_slug=hyein-seo&discount_from=60&final_price_to=200&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Japaneese brands"
    },
    {
        "url": "https://www.lyst.com/shop/mens-clothing/?discount_from=68&final_price_from=50&final_price_to=180&retailer_slug=jomashop-us&view=price_asc",
        "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
        "min_sale": 50,
        "url_name": "Jomashop"
    },
        #    {
    #     "url": "https://www.lyst.com/shop/mens-clothing/?designer_slug=mastermind-japan&designer_slug=mastermind-world&discount_from=60",
    #     "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID, 
    #     "min_sale": 50,
    #     "url_name": "test brands"
    # },
    # {
    #     "url": "https://www.lyst.com/shop/mens-shoes/?designer_slug=eytys&designer_slug=hereu-designer&designer_slug=grenson&designer_slug=drae&designer_slug=copenhagen&designer_slug=a-diciannoveventitre&designer_slug=kleman&designer_slug=tiger-of-sweden&designer_slug=nanamica&designer_slug=marsell&designer_slug=norse-projects-arktisk&designer_slug=drae&designer_slug=maison-martin-margiela&designer_slug=magliano&designer_slug=mm6-by-maison-martin-margiela&designer_slug=camperlab&designer_slug=yume_yume&designer_slug=dries-van-noten&designer_slug=our-legacy&designer_slug=stefan-cooke&designer_slug=adieu&designer_slug=c2h4&designer_slug=lanvin&designer_slug=acne&designer_slug=a_cold_wall&designer_slug=raf-simons&designer_slug=raf-simons-runner&designer_slug=axel-arigato&designer_slug=y-3&designer_slug=prada&designer_slug=roa-designer&designer_slug=wooyoungmi&designer_slug=maison-margiela-x-reebok&designer_slug=424&designer_slug=jil-sander&designer_slug=juunj&designer_slug=kenzo&designer_slug=oamc&designer_slug=1017-alyx-9sm&designer_slug=officine-creative&designer_slug=marine-serre&designer_slug=salomon&designer_slug=moncler&designer_slug=maison-mihara-yasuhiro-designer&designer_slug=comme-des-garcons&designer_slug=ami&designer_slug=rick-owens-drkshdw&designer_slug=marni&designer_slug=boris-bidjan-saberi-11&designer_slug=merrell&designer_slug=norse-projects&designer_slug=demon-designer&designer_slug=toga-virilis&designer_slug=gucci&designer_slug=kiko-kostadinov&designer_slug=fracap&designer_slug=golden-goose-deluxe-brand&designer_slug=sacai&designer_slug=ann-demeulemeester&designer_slug=diemme&designer_slug=gmbh&designer_slug=rombaut&designer_slug=both-paris&designer_slug=stone-island&designer_slug=jacquemus&designer_slug=jw-anderson&designer_slug=givenchy&designer_slug=sandro&designer_slug=hender-scheme&designer_slug=buttero&designer_slug=bottega-veneta&designer_slug=alexander-mcqueen&designer_slug=balenciaga&designer_slug=44-label-group&designer_slug=gr10k&designer_slug=uma-wang&designer_slug=undercover&designer_slug=iro&designer_slug=ganni&designer_slug=ernest-w-baker&designer_slug=andersson-bell-designer&discount_from=71&final_price_from=200&final_price_to=250&instock_size=size.footwear.eu.u.40&instock_size=size.footwear.eu.u.40%275&instock_size=size.footwear.eu.u.41&sizes=IT+40.0&sizes=IT+40.5&sizes=IT+41.0&view=price_asc",
    #     "telegram_chat_id": DANYLO_DEFAULT_CHAT_ID,
    #     "min_sale": 50,
    #     "url_name": "Grotesk Pricy Shoes"
    # },
]
